name: Deploy DAGs to Airflow VM

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH for deployment
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Sync DAGs to Airflow VM
        run: rsync -avz -e "ssh -o StrictHostKeyChecking=no" ./dags/ tobi@35.205.108.18:/home/liquid-kite-436018-c2/airflow/dags

      - name: Restart Airflow Scheduler and Webserver
        run: |
          ssh -o StrictHostKeyChecking=no user@your_vm_ip 'sudo systemctl restart airflow-scheduler && sudo systemctl restart airflow-webserver'
